import {
  Card,
  CardContent,
  Typography,
  Chip,
  Stack,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Paper,
  Divider,
} from "@mui/material";

import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import DescriptionIcon from "@mui/icons-material/Description";
import SmartToyIcon from "@mui/icons-material/SmartToy";

import ReactMarkdown from "react-markdown";

function ResultCard({ result }) {
  if (!result) return null;

  const cleanOutput = (text) =>
    text ? text.replace(/\x1B\[[0-9;]*m/g, "") : "";

  return (
    <Stack spacing={3}>
      {result.results.map((item, index) => (
        <Card
          key={index}
          elevation={3}
          sx={{
            borderRadius: 3,
          }}
        >
          <CardContent sx={{ p: 3 }}>

            {/* File Header */}
            <Stack
              direction={{ xs: "column", sm: "row" }}
              justifyContent="space-between"
              alignItems={{ xs: "flex-start", sm: "center" }}
              spacing={2}
              mb={2}
            >
              <Stack direction="row" spacing={2} alignItems="center">
                <DescriptionIcon color="primary" />

                <Stack spacing={0.5}>
                  <Typography variant="h6" fontWeight="bold">
                    {item.file}
                  </Typography>

                  <Chip
                    label={item.type || "Terraform"}
                    size="small"
                    color="primary"
                  />
                </Stack>
              </Stack>

              <Chip
                label={item.status}
                color={
                  item.status === "PASS"
                    ? "success"
                    : "error"
                }
                sx={{ fontWeight: "bold" }}
              />
            </Stack>

            <Divider sx={{ mb: 3 }} />

            {/* Validation Output */}
            <Typography
              variant="subtitle1"
              fontWeight="bold"
              sx={{ mb: 1.5 }}
            >
              Validation Output
            </Typography>

            <Paper
              variant="outlined"
              sx={{
                p: 2,
                backgroundColor: "#f8fafc",
                borderRadius: 2,
                overflowX: "auto",
              }}
            >
              <Typography
                component="pre"
                sx={{
                  margin: 0,
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                  fontFamily: "Consolas, monospace",
                  fontSize: "0.95rem",
                  lineHeight: 1.7,
                }}
              >
                {cleanOutput(item.output || item.reason)}
              </Typography>
            </Paper>

            {/* AI Recommendation */}
            {item.ai_explanation && (
              <Accordion
                sx={{
                  mt: 3,
                  borderRadius: "8px !important",
                  "&:before": {
                    display: "none",
                  },
                }}
              >
                <AccordionSummary
                  expandIcon={<ExpandMoreIcon />}
                >
                  <Stack
                    direction="row"
                    spacing={1.5}
                    alignItems="center"
                  >
                    <SmartToyIcon color="primary" />

                    <Stack>
                      <Typography fontWeight="bold">
                        AI Security Analysis
                      </Typography>

                      <Typography
                        variant="caption"
                        color="text.secondary"
                      >
                        Generated by{" "}
                        {item.ai_provider || "AI"}
                      </Typography>
                    </Stack>
                  </Stack>
                </AccordionSummary>

                <AccordionDetails>
                  <Paper
                    variant="outlined"
                    sx={{
                      p: 3,
                      backgroundColor: "#fafafa",
                      borderRadius: 2,
                    }}
                  >
                    <ReactMarkdown
                      components={{
                        h1: ({ children }) => (
                          <Typography
                            variant="h5"
                            fontWeight="bold"
                            sx={{ mt: 1, mb: 2 }}
                          >
                            {children}
                          </Typography>
                        ),

                        h2: ({ children }) => (
                          <Typography
                            variant="h6"
                            fontWeight="bold"
                            sx={{ mt: 3, mb: 1 }}
                          >
                            {children}
                          </Typography>
                        ),

                        h3: ({ children }) => (
                          <Typography
                            variant="subtitle1"
                            fontWeight="bold"
                            sx={{ mt: 2, mb: 1 }}
                          >
                            {children}
                          </Typography>
                        ),

                        p: ({ children }) => (
                          <Typography
                            sx={{
                              lineHeight: 1.8,
                              mb: 2,
                            }}
                          >
                            {children}
                          </Typography>
                        ),

                        ul: ({ children }) => (
                          <BoxList>{children}</BoxList>
                        ),

                        li: ({ children }) => (
                          <li>
                            <Typography
                              component="span"
                              sx={{ lineHeight: 1.8 }}
                            >
                              {children}
                            </Typography>
                          </li>
                        ),

                        code: ({
                          inline,
                          children,
                        }) =>
                          inline ? (
                            <code
                              style={{
                                background: "#eef2ff",
                                padding: "2px 6px",
                                borderRadius: "4px",
                              }}
                            >
                              {children}
                            </code>
                          ) : (
                            <Paper
                              sx={{
                                p: 2,
                                mb: 2,
                                backgroundColor: "#111827",
                                color: "#fff",
                                overflowX: "auto",
                              }}
                            >
                              <Typography
                                component="pre"
                                sx={{
                                  margin: 0,
                                  fontFamily:
                                    "Consolas, monospace",
                                  fontSize: "0.9rem",
                                }}
                              >
                                {children}
                              </Typography>
                            </Paper>
                          ),
                      }}
                    >
                      {item.ai_explanation}
                    </ReactMarkdown>
                  </Paper>
                </AccordionDetails>
              </Accordion>
            )}
          </CardContent>
        </Card>
      ))}
    </Stack>
  );
}

/* Small helper for Markdown lists */
function BoxList({ children }) {
  return (
    <ul
      style={{
        paddingLeft: "24px",
        marginBottom: "16px",
      }}
    >
      {children}
    </ul>
  );
}

export default ResultCard;